language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -f udagram-feed-api/Dockerfile -t  ashioyajotham/udagram-feed-api:latest udagram-feed-api
  - docker build -f udagram-user-api/Dockerfile -t  ashioyajotham/udagram-user-api:latest udagram-user-api
  - docker build -f udagram-frontend/Dockerfile -t  ashioyajotham/udagram-frontend:latest udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  ashioyajotham/udagram-reverseproxy:latest udagram-reverseproxy


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ashioyajotham/udagram-reverseproxy:latest
  - docker push ashioyajotham/udagram-user-api:latest
  - docker push ashioyajotham/udagram-feed-api:latest
  - docker push ashioyajotham/udagram-frontend:latest