language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-reverseproxy ashioyajotham/udagram-reverseproxy:latest
  - docker tag udagram-user-api ashioyajotham/udagram-user-api:latest
  - docker tag udagram-feed-api ashioyajotham/udagram-feed-api:latest
  - docker tag udagram-frontend ashioyajotham/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ashioyajotham/udagram-reverseproxy:latest
  - docker push ashioyajotham/udagram-user-api:latest
  - docker push ashioyajotham/udagram-feed-api:latest
  - docker push ashioyajotham/udagram-frontend:latest