apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-service
  labels:
    app: udagram-reverseproxy
spec:
  selector:
    app: udagram-reverseproxy
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080